- type: civic
  length: 100
  width: 70
  image: civic.png
- type: mercedes
  length: 100
  width: 70
  image: mercedes.png
- type: r34
  length: 100
  width: 70
  image: r34.png
- type: supra
  length: 100
  width: 70
  image: supra.png
- type: traffic1
  length: 100
  width: 70
  image: traffic_car2.png
- type: traffic1
  length: 100
  width: 70
  image: traffic_car2.png
- type: traffic3
  length: 100
  width: 70
  image: traffic_car3.png


