- type: traffic1
  length: 211
  width: 90
  image: traffic_car1.png
- type: traffic2
  length: 211
  width: 90
  image: traffic_car2.png
- type: traffic3
  length: 211
  width: 90
  image: traffic_car3.png
- type: traffic4
  length: 200
  width: 90
  image: traffic_car4.png
- type: traffic5
  length: 215
  width: 93
  image: traffic_car5.png
- type: traffic6
  length: 220
  width: 95
  image: traffic_car6.png
- type: traffic7
  length: 197
  width: 90
  image: traffic_car7.png
- type: traffic8
  length: 234
  width: 90
  image: traffic_car8.png

